# generated by datamodel-codegen:
#   filename:  attachment.json
#   timestamp: 2026-04-17T13:46:10+00:00

from __future__ import annotations

from typing import Annotated, Literal
from uuid import UUID

from pydantic import AwareDatetime, BaseModel, ConfigDict, Field


class Attachment(BaseModel):
    """
    DB-mirrored pointer record for an uploaded multimodal asset.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    id: UUID
    organization_id: UUID
    run_id: Annotated[str, Field(max_length=64)]
    tool_call_id: Annotated[str | None, Field(max_length=128)] = None
    blob_key: str
    mime: Literal['image/png', 'image/jpeg', 'image/gif', 'image/webp']
    size_bytes: Annotated[int, Field(ge=0)]
    width: Annotated[int | None, Field(ge=1)] = None
    height: Annotated[int | None, Field(ge=1)] = None
    role: Literal['input', 'tool_response']
    upload_status: Literal['pending', 'complete', 'failed']
    sha256: Annotated[str | None, Field(max_length=64)] = None
    created_at: AwareDatetime
    soft_deleted_at: AwareDatetime | None = None
