# generated by datamodel-codegen:
#   filename:  chat-message.json
#   timestamp: 2026-04-17T13:46:10+00:00

from __future__ import annotations

from typing import Literal

from pydantic import BaseModel, ConfigDict

from . import content_block


class ChatMessage(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    role: Literal['user', 'assistant', 'system', 'tool']
    content: str | list[content_block.ContentBlock]
    tool_call_id: str | None = None
    name: str | None = None
