# generated by datamodel-codegen:
#   filename:  content-block.json
#   timestamp: 2026-04-17T13:46:10+00:00

from __future__ import annotations

from typing import Annotated, Literal
from uuid import UUID

from pydantic import AnyUrl, AwareDatetime, BaseModel, ConfigDict, Field, RootModel


class TextContent(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    type: Literal['text']
    text: str


class ImageSourceBase64(BaseModel):
    """
    Raw base64-encoded image. Used by SDK -> API on ingest, and engine -> provider at inference boundary.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    kind: Literal['base64']
    data: str
    """
    raw base64, no data: prefix
    """
    mime: Literal['image/png', 'image/jpeg', 'image/gif', 'image/webp']


class ImageSourceBlobRef(BaseModel):
    """
    Canonical storage/stream form. The only variant allowed in S2 frames and DB records.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    kind: Literal['blob_ref']
    blob_key: Annotated[str, Field(pattern='^org/[0-9a-f-]{36}/run/[^/]+/')]
    mime: Literal['image/png', 'image/jpeg', 'image/gif', 'image/webp']
    width: Annotated[int | None, Field(ge=1)] = None
    height: Annotated[int | None, Field(ge=1)] = None
    size_bytes: Annotated[int | None, Field(ge=0)] = None
    attachment_id: UUID | None = None
    presigned_url: AnyUrl | None = None
    presigned_expires_at: AwareDatetime | None = None
    upload_status: Literal['pending', 'complete', 'failed'] | None = None


class ImageSourceUrl(BaseModel):
    """
    Out-of-band source. Server may resolve to blob_ref on ingest or pass through to vendor (vendor-fetchable only).
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    kind: Literal['url']
    url: AnyUrl
    mime: Literal['image/png', 'image/jpeg', 'image/gif', 'image/webp'] | None = None


class ImageContent(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    type: Literal['image']
    source: ImageSourceBase64 | ImageSourceBlobRef | ImageSourceUrl


class ContentBlock(RootModel[TextContent | ImageContent]):
    root: Annotated[TextContent | ImageContent, Field(title='ContentBlock')]
    """
    A single block of message content. Discriminated on `type`.
    """
