# generated by datamodel-codegen:
#   filename:  create-attachment-response.json
#   timestamp: 2026-04-17T13:46:10+00:00

from __future__ import annotations

from typing import Literal
from uuid import UUID

from pydantic import AnyUrl, AwareDatetime, BaseModel, ConfigDict


class CreateAttachmentResponse(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    attachment_id: UUID
    blob_key: str
    presigned_url: AnyUrl
    presigned_expires_at: AwareDatetime
    upload_status: Literal['pending', 'complete', 'failed']
