# generated by datamodel-codegen:
#   filename:  create-attachment-request.json
#   timestamp: 2026-04-17T13:46:10+00:00

from __future__ import annotations

from typing import Literal
from uuid import UUID

from pydantic import BaseModel, ConfigDict


class Image(BaseModel):
    base64: str
    blob_key: str | None = None
    mime: Literal['image/png', 'image/jpeg', 'image/gif', 'image/webp']
    width: int | None = None
    height: int | None = None
    size_bytes: int | None = None


class Image1(BaseModel):
    base64: str | None = None
    blob_key: str
    mime: Literal['image/png', 'image/jpeg', 'image/gif', 'image/webp']
    width: int | None = None
    height: int | None = None
    size_bytes: int | None = None


class CreateAttachmentRequest(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    run_id: str
    organization_id: UUID
    tool_call_id: str | None = None
    role: Literal['input', 'tool_response']
    image: Image | Image1
