# generated by datamodel-codegen:
#   filename:  tool.json
#   timestamp: 2026-04-17T13:46:10+00:00

from __future__ import annotations

from typing import Annotated, Any

from pydantic import BaseModel, ConfigDict, Field, RootModel

from . import content_block


class Tool(RootModel[Any]):
    root: Annotated[Any, Field(title='Tool')]


class ToolCall(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: str
    name: Annotated[str, Field(pattern='^[a-zA-Z_][a-zA-Z0-9_-]*$')]
    arguments: dict[str, Any]


class ToolResponse(BaseModel):
    """
    Standardized tool-output envelope. A screenshot tool returns [{ type: image, source: { kind: base64, ... } }]. Text tools return [{ type: text, text: ... }].
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    tool_call_id: str
    content: list[content_block.ContentBlock]
    is_error: bool | None = False
